[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
user=root

[unix_http_server]
file=/var/run/supervisor.sock

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:laravel-app]
process_name=%(program_name)s
command=php /app/artisan serve --host=0.0.0.0 --port=8000
autostart=true
autorestart=true
numprocs=1
redirect_stderr=true
stdout_logfile=/app/storage/logs/app.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=10
user=www-data
stopasgroup=true
killasgroup=true

[program:laravel-monitor]
process_name=%(program_name)s
command=php /app/artisan so:monitor
autostart=true
autorestart=true
numprocs=1
redirect_stderr=true
stdout_logfile=/app/storage/logs/monitor.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=10
user=www-data
stopasgroup=true
killasgroup=true
startsecs=5
priority=999

[group:laravel-services]
programs=laravel-app,laravel-monitor
